[2024-05-08T21:56:47.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T21:56:47.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 10_branching.branch scheduled__2022-07-07T00:00:00+00:00 [queued]>
[2024-05-08T21:56:47.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 10_branching.branch scheduled__2022-07-07T00:00:00+00:00 [queued]>
[2024-05-08T21:56:47.856+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-08T21:56:47.907+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch> on 2022-07-07 00:00:00+00:00
[2024-05-08T21:56:47.939+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '10_branching', 'branch', 'scheduled__2022-07-07T00:00:00+00:00', '--job-id', '859', '--raw', '--subdir', 'DAGS_FOLDER/10_branchpythonoperator.py', '--cfg-path', '/tmp/tmp4py7y810']
[2024-05-08T21:56:47.939+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3950) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T21:56:47.955+0000] {standard_task_runner.py:91} INFO - Job 859: Subtask branch
[2024-05-08T21:56:47.956+0000] {standard_task_runner.py:63} INFO - Started process 3961 to run task
[2024-05-08T21:56:48.266+0000] {task_command.py:426} INFO - Running <TaskInstance: 10_branching.branch scheduled__2022-07-07T00:00:00+00:00 [running]> on host ccc314eb571d
[2024-05-08T21:56:48.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='10_branching' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2022-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-07T00:00:00+00:00'
[2024-05-08T21:56:48.604+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T21:56:48.679+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-08T21:56:48.681+0000] {python.py:237} INFO - Done. Returned value was: finish_14_june
[2024-05-08T21:56:48.683+0000] {branch.py:36} INFO - Branch into finish_14_june
[2024-05-08T21:56:48.685+0000] {skipmixin.py:178} INFO - Following branch finish_14_june
[2024-05-08T21:56:48.737+0000] {skipmixin.py:246} INFO - Skipping tasks [('start_15_june', -1)]
[2024-05-08T21:56:48.858+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T21:56:48.903+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=10_branching, task_id=branch, run_id=scheduled__2022-07-07T00:00:00+00:00, execution_date=20220707T000000, start_date=20240508T215647, end_date=20240508T215648
[2024-05-08T21:56:49.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-08T21:56:49.258+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-08T21:56:49.268+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
