[2024-05-08T00:28:29.137+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T00:28:29.157+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1_monitoring.tarea2 scheduled__2024-01-28T00:00:00+00:00 [queued]>
[2024-05-08T00:28:29.164+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1_monitoring.tarea2 scheduled__2024-01-28T00:00:00+00:00 [queued]>
[2024-05-08T00:28:29.165+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-08T00:28:29.180+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): tarea2> on 2024-01-28 00:00:00+00:00
[2024-05-08T00:28:29.186+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4814) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T00:28:29.187+0000] {standard_task_runner.py:63} INFO - Started process 4839 to run task
[2024-05-08T00:28:29.187+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '6.1_monitoring', 'tarea2', 'scheduled__2024-01-28T00:00:00+00:00', '--job-id', '434', '--raw', '--subdir', 'DAGS_FOLDER/061_monitoring.py', '--cfg-path', '/tmp/tmput1ajj6p']
[2024-05-08T00:28:29.188+0000] {standard_task_runner.py:91} INFO - Job 434: Subtask tarea2
[2024-05-08T00:28:29.229+0000] {task_command.py:426} INFO - Running <TaskInstance: 6.1_monitoring.tarea2 scheduled__2024-01-28T00:00:00+00:00 [running]> on host 521bf890d837
[2024-05-08T00:28:29.310+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1_monitoring' AIRFLOW_CTX_TASK_ID='tarea2' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-28T00:00:00+00:00'
[2024-05-08T00:28:29.311+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T00:28:29.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-08T00:28:29.325+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 2 && echo 'Segunda tarea!'"]
[2024-05-08T00:28:29.334+0000] {subprocess.py:86} INFO - Output:
[2024-05-08T00:28:31.339+0000] {subprocess.py:93} INFO - Segunda tarea!
[2024-05-08T00:28:31.340+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-08T00:28:31.345+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T00:28:31.371+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=6.1_monitoring, task_id=tarea2, run_id=scheduled__2024-01-28T00:00:00+00:00, execution_date=20240128T000000, start_date=20240508T002829, end_date=20240508T002831
[2024-05-08T00:28:31.490+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-08T00:28:31.513+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-08T00:28:31.519+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
