[2024-05-08T00:25:57.945+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T00:25:57.962+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1_monitoring.tarea2 scheduled__2024-01-15T00:00:00+00:00 [queued]>
[2024-05-08T00:25:57.968+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1_monitoring.tarea2 scheduled__2024-01-15T00:00:00+00:00 [queued]>
[2024-05-08T00:25:57.969+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-08T00:25:57.980+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): tarea2> on 2024-01-15 00:00:00+00:00
[2024-05-08T00:25:57.985+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4516) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T00:25:57.987+0000] {standard_task_runner.py:63} INFO - Started process 4517 to run task
[2024-05-08T00:25:57.986+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '6.1_monitoring', 'tarea2', 'scheduled__2024-01-15T00:00:00+00:00', '--job-id', '354', '--raw', '--subdir', 'DAGS_FOLDER/061_monitoring.py', '--cfg-path', '/tmp/tmpt9j964ss']
[2024-05-08T00:25:57.988+0000] {standard_task_runner.py:91} INFO - Job 354: Subtask tarea2
[2024-05-08T00:25:58.063+0000] {task_command.py:426} INFO - Running <TaskInstance: 6.1_monitoring.tarea2 scheduled__2024-01-15T00:00:00+00:00 [running]> on host 521bf890d837
[2024-05-08T00:25:58.123+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1_monitoring' AIRFLOW_CTX_TASK_ID='tarea2' AIRFLOW_CTX_EXECUTION_DATE='2024-01-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-15T00:00:00+00:00'
[2024-05-08T00:25:58.124+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T00:25:58.134+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-08T00:25:58.135+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 2 && echo 'Segunda tarea!'"]
[2024-05-08T00:25:58.142+0000] {subprocess.py:86} INFO - Output:
[2024-05-08T00:26:00.145+0000] {subprocess.py:93} INFO - Segunda tarea!
[2024-05-08T00:26:00.145+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-08T00:26:00.146+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T00:26:00.167+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=6.1_monitoring, task_id=tarea2, run_id=scheduled__2024-01-15T00:00:00+00:00, execution_date=20240115T000000, start_date=20240508T002557, end_date=20240508T002600
[2024-05-08T00:26:00.212+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-08T00:26:00.233+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-08T00:26:00.238+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
