[2024-05-10T06:22:56.295+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T06:22:56.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Respuesta_Satelite scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-05-10T06:22:56.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Proyecto_SpaceX_v1.Respuesta_Satelite scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-05-10T06:22:56.447+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-10T06:22:56.459+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Respuesta_Satelite> on 2024-03-23 00:00:00+00:00
[2024-05-10T06:22:56.466+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2050) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T06:22:56.467+0000] {standard_task_runner.py:63} INFO - Started process 2052 to run task
[2024-05-10T06:22:56.467+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Proyecto_SpaceX_v1', 'Respuesta_Satelite', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '1284', '--raw', '--subdir', 'DAGS_FOLDER/Proyecto_SpaceX_v1.py', '--cfg-path', '/tmp/tmpzxqbtahm']
[2024-05-10T06:22:56.469+0000] {standard_task_runner.py:91} INFO - Job 1284: Subtask Respuesta_Satelite
[2024-05-10T06:22:56.509+0000] {task_command.py:426} INFO - Running <TaskInstance: Proyecto_SpaceX_v1.Respuesta_Satelite scheduled__2024-03-23T00:00:00+00:00 [running]> on host 1b7f0b10dd99
[2024-05-10T06:22:56.583+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Proyecto_SpaceX_v1' AIRFLOW_CTX_TASK_ID='Respuesta_Satelite' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-05-10T06:22:56.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T06:22:56.600+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-10T06:22:56.602+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T06:22:56.609+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Proyecto_SpaceX_v1, task_id=Respuesta_Satelite, run_id=scheduled__2024-03-23T00:00:00+00:00, execution_date=20240323T000000, start_date=20240510T062256, end_date=20240510T062256
[2024-05-10T06:22:56.642+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T06:22:56.662+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-10T06:22:56.665+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
