[2024-05-08T00:28:37.627+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T00:28:37.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6.1_monitoring.tarea5 scheduled__2024-01-22T00:00:00+00:00 [queued]>
[2024-05-08T00:28:37.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6.1_monitoring.tarea5 scheduled__2024-01-22T00:00:00+00:00 [queued]>
[2024-05-08T00:28:37.678+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-08T00:28:37.707+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): tarea5> on 2024-01-22 00:00:00+00:00
[2024-05-08T00:28:37.715+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4959) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T00:28:37.717+0000] {standard_task_runner.py:63} INFO - Started process 4974 to run task
[2024-05-08T00:28:37.717+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '6.1_monitoring', 'tarea5', 'scheduled__2024-01-22T00:00:00+00:00', '--job-id', '474', '--raw', '--subdir', 'DAGS_FOLDER/061_monitoring.py', '--cfg-path', '/tmp/tmpf5c_4hri']
[2024-05-08T00:28:37.719+0000] {standard_task_runner.py:91} INFO - Job 474: Subtask tarea5
[2024-05-08T00:28:37.795+0000] {task_command.py:426} INFO - Running <TaskInstance: 6.1_monitoring.tarea5 scheduled__2024-01-22T00:00:00+00:00 [running]> on host 521bf890d837
[2024-05-08T00:28:37.930+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='6.1_monitoring' AIRFLOW_CTX_TASK_ID='tarea5' AIRFLOW_CTX_EXECUTION_DATE='2024-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-22T00:00:00+00:00'
[2024-05-08T00:28:37.931+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T00:28:37.952+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-08T00:28:37.954+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 2 && echo 'Cuarta tarea!'"]
[2024-05-08T00:28:37.967+0000] {subprocess.py:86} INFO - Output:
[2024-05-08T00:28:39.971+0000] {subprocess.py:93} INFO - Cuarta tarea!
[2024-05-08T00:28:39.971+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-08T00:28:39.972+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T00:28:39.997+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=6.1_monitoring, task_id=tarea5, run_id=scheduled__2024-01-22T00:00:00+00:00, execution_date=20240122T000000, start_date=20240508T002837, end_date=20240508T002839
[2024-05-08T00:28:40.023+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-08T00:28:40.045+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-08T00:28:40.050+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
